# Generated by Django 5.0.4 on 2024-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_libro', models.CharField(max_length=255)),
                ('nom_autor', models.CharField(max_length=255)),
                ('edicion', models.CharField(max_length=255)),
                ('colocacion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('matricula', models.IntegerField()),
                ('nom_alumno', models.CharField(max_length=255)),
                ('carrera_grupo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'prestamos',
                'verbose_name_plural': 'prestamos',
            },
        ),
    ]
