# Generated by Django 5.0.4 on 2024-11-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_model_catalogo_tipop'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_catalogo',
            name='fechaP',
            field=models.DateTimeField(null=True, verbose_name='fechaP'),
        ),
    ]
