# Generated by Django 5.0.4 on 2024-11-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_model_catalogo_fechap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_catalogo',
            name='tipoP',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
