# Generated by Django 5.0.4 on 2024-11-27 08:18

import catalogo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_model_catalogo_tipop'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_catalogo',
            name='base64',
            field=catalogo.models.LongTextField(blank=True, null=True, verbose_name='Portada'),
        ),
    ]
