# Generated by Django 5.0.4 on 2024-12-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_model_catalogo_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_catalogo',
            name='base64',
        ),
        migrations.AddField(
            model_name='model_catalogo',
            name='entrega',
            field=models.CharField(blank=True, choices=[('No/entragado', 'No/entragado'), ('Entragado', 'Entragado')], default='No/entragado', max_length=255, null=True, verbose_name='Tipo de entrega'),
        ),
    ]
