# Generated by Django 5.0.4 on 2024-12-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_model_catalogo_base64_model_catalogo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_catalogo',
            name='entrega',
            field=models.CharField(blank=True, choices=[('No/entregado', 'No/entregado'), ('Entregado', 'Entregado')], default='No/entregado', max_length=255, null=True, verbose_name='Tipo de entrega'),
        ),
    ]
