# Generated by Django 5.0.4 on 2024-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_model_catalogo_fechae_alter_model_catalogo_fechap'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_catalogo',
            name='cve_prestamo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
