# Generated by Django 5.0.4 on 2024-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_model_catalogo_cve_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_catalogo',
            name='fechaE',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha entrega'),
        ),
        migrations.AlterField(
            model_name='model_catalogo',
            name='fechaP',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha prestamo'),
        ),
    ]
