# Generated by Django 5.0.4 on 2024-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_alter_model_catalogo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_catalogo',
            name='fechaD',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha devuelto'),
        ),
    ]
