# Generated by Django 5.0.4 on 2024-12-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_model_catalogo_fechad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_catalogo',
            name='entrega',
            field=models.CharField(blank=True, choices=[('No/entregado', 'No/entregado'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Proceso', 'Proceso')], default='No/entregado', max_length=255, null=True, verbose_name='Tipo de entrega'),
        ),
    ]
