# Generated by Django 5.0.4 on 2024-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_alter_model_catalogo_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_catalogo',
            old_name='cantidad',
            new_name='cantidad_i',
        ),
        migrations.AddField(
            model_name='model_catalogo',
            name='cantidad_m',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
