# Generated by Django 5.0.4 on 2025-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_rename_cantidad_model_catalogo_cantidad_i_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_catalogo',
            name='formatoejem',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
