# Generated by Django 5.0.6 on 2024-07-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarioacceso',
            table='sistema_usuario',
        ),
    ]
