# Generated by Django 5.0.4 on 2025-05-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_usuarioacceso_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioacceso',
            options={'managed': False, 'verbose_name': 'Acceso Usuario', 'verbose_name_plural': 'Acceso Usuarios'},
        ),
    ]
