# Generated by Django 5.0.4 on 2024-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acervo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('colocacion', models.CharField(max_length=50, verbose_name='Colocación')),
                ('edicion', models.CharField(max_length=50, verbose_name='Edición')),
                ('año', models.IntegerField(verbose_name='Año de edición')),
                ('fechaRegistro', models.DateField(verbose_name='Fecha de Registro')),
            ],
        ),
    ]
