# Generated by Django 5.0.4 on 2024-05-16 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervo_model',
            name='estado',
            field=models.CharField(choices=[('EXC', 'Excelente'), ('REG', 'Regular'), ('BUE', 'Bueno'), ('MAL', 'Malo')], default='EXC', max_length=3, verbose_name='Estado del libro'),
        ),
        migrations.AddField(
            model_name='acervo_model',
            name='type_adqui',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Tipo de adquisición'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='colocacion',
            field=models.CharField(choices=[('ADM', 'Administración'), ('PIA', 'Procesos_I'), ('MET', 'Macarrónica'), ('ERC', 'Energías_R'), ('QUIM', 'Química'), ('TIS', 'Tecnologías_I'), ('CBA', 'Ciencias_B_A'), ('FSC', 'Formación_S'), ('OCL', 'Otros_C'), ('OCLEC', 'Lectura'), ('OCA', 'Adicciones'), ('OCIG', 'Igualdad'), ('FCE', 'Colecciones_C'), ('IDI', 'Idiomas'), ('IDF', 'Francés'), ('LYMd', 'Consulta_Audiovisual'), ('ADMd', 'Consulta_Audiovisual'), ('QUIMd', 'Consulta_Audiovisual'), ('METd', 'Consulta_Audiovisual'), ('PIAd', 'Consulta_Audiovisual'), ('ERCd', 'Consulta_Audiovisual'), ('CBAd', 'Consulta_Audiovisual'), ('FSCd', 'Consulta_Audiovisual'), ('OCId', 'Consulta_Audiovisual'), ('TISd', 'Consulta_Audiovisual'), ('OC', 'Hemerografico'), ('OTROS', 'Otros')], default='ADM', max_length=6, verbose_name='Colocación'),
        ),
    ]
