# Generated by Django 5.0.4 on 2024-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_remove_acervo_model_numer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='colocacion',
            field=models.CharField(max_length=100, verbose_name='Colocación'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='edicion',
            field=models.CharField(max_length=100, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='estado',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='Excelente', max_length=100, verbose_name='Estado del libro'),
        ),
    ]
