# Generated by Django 5.0.6 on 2024-06-21 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_remove_acervo_model_type_adqui_acervo_model_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervo_model',
            name='adqui',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Tipo de adquisición'),
            preserve_default=False,
        ),
    ]
