# Generated by Django 5.0.6 on 2024-06-22 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_acervo_model_adqui'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acervo_model',
            old_name='año',
            new_name='anio',
        ),
    ]
