# Generated by Django 5.0.6 on 2024-06-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_rename_año_acervo_model_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='adqui',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de adquisición'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='anio',
            field=models.IntegerField(blank=True, verbose_name='Año de edición'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='autor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='cant',
            field=models.IntegerField(blank=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='colocacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Colocación'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='edicion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='editorial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='estado',
            field=models.CharField(blank=True, choices=[('EXC', 'Excelente'), ('BUE', 'Bueno'), ('REG', 'Regular'), ('MAL', 'Malo')], default='EXC', max_length=3, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='fechaRegistro',
            field=models.DateField(blank=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='formato',
            field=models.CharField(blank=True, choices=[('book', 'Libro'), ('disc', 'Disco')], default='book', max_length=5, verbose_name='formato'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo'),
        ),
    ]
