# Generated by Django 5.0.6 on 2024-06-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_alter_acervo_model_adqui_alter_acervo_model_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='anio',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Año de edición'),
        ),
    ]
