# Generated by Django 5.0.4 on 2024-11-28 07:36

import almacen.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0016_rename_fecha_edicion_acervo_model_fechaedicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervo_model',
            name='base64',
            field=almacen.models.LongTextField(blank=True, null=True, verbose_name='Portada'),
        ),
    ]
