# Generated by Django 5.0.4 on 2024-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0017_acervo_model_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='formato',
            field=models.CharField(blank=True, choices=[('Libro', 'Libro'), ('Disco', 'Disco')], default='Libro', max_length=5, null=True, verbose_name='formato'),
        ),
    ]
