# Generated by Django 5.0.4 on 2024-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_alter_acervo_model_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='estado',
            field=models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], default='Excelente', max_length=11, null=True, verbose_name='Estado'),
        ),
    ]
