# Generated by Django 5.0.4 on 2024-12-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0020_alter_acervo_model_estado_alter_acervo_model_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='acervo_model',
            name='clave',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Clave'),
        ),
    ]
