# Generated by Django 5.0.4 on 2024-12-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0021_acervo_model_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acervo_model',
            name='clave',
        ),
    ]
