# Generated by Django 5.0.4 on 2025-03-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0022_remove_acervo_model_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='formato',
            field=models.CharField(blank=True, choices=[('Libro', 'Libro'), ('Disco', 'Disco'), ('Revista', 'Revista')], default='Libro', max_length=7, null=True, verbose_name='formato'),
        ),
    ]
