# Generated by Django 5.0.4 on 2025-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0023_alter_acervo_model_formato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='fechaedicion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='fecharegistro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
