# Generated by Django 5.0.4 on 2025-05-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0024_alter_acervo_model_fechaedicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acervo_model',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='acervo_model',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='titulo'),
        ),
    ]
