# Generated by Django 5.0.4 on 2024-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadias',
            name='convenio',
            field=models.FileField(null=True, upload_to='documentos_pdf/'),
        ),
    ]
