# Generated by Django 5.0.4 on 2024-05-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0002_alter_estadias_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadias',
            name='c_aceptacion',
            field=models.FileField(null=True, upload_to='archivos_estadias/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='convenio',
            field=models.FileField(null=True, upload_to='archivos_estadias/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='cronograma',
            field=models.FileField(null=True, upload_to='archivos_estadias/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='reporte',
            field=models.FileField(null=True, upload_to='archivos_estadias/'),
        ),
    ]
