# Generated by Django 5.0.4 on 2024-06-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0004_alter_estadias_c_aceptacion_alter_estadias_convenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadias',
            name='c_aceptacion',
            field=models.FileField(null=True, upload_to='c_aceptacion/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='convenio',
            field=models.FileField(null=True, upload_to='convenio/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='cronograma',
            field=models.FileField(null=True, upload_to='cronograma/'),
        ),
        migrations.AlterField(
            model_name='estadias',
            name='reporte',
            field=models.FileField(null=True, upload_to='reporte/'),
        ),
    ]
