# Generated by Django 5.0.6 on 2024-06-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0005_alter_estadias_c_aceptacion_alter_estadias_convenio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadias',
            name='c_aceptacion',
        ),
        migrations.RemoveField(
            model_name='estadias',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='estadias',
            name='cronograma',
        ),
    ]
