# Generated by Django 5.0.6 on 2024-08-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0008_rename_asesor_empresarial_estadias_asesor_orga'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estadias',
            new_name='model_estadias',
        ),
    ]
