# Generated by Django 5.0.6 on 2024-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0009_rename_estadias_model_estadias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model_estadias',
            options={'verbose_name': 'estadía', 'verbose_name_plural': 'estadías'},
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='alumno',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='asesor_academico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='asesor_orga',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='generacion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='proyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='reporte',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Reporte'),
        ),
    ]
