# Generated by Django 5.0.6 on 2024-10-13 20:44

import estadias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0013_alter_model_estadias_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_estadias',
            name='base64',
            field=estadias.models.LongTextField(blank=True, null=True, verbose_name='Reporte'),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='reporte',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
