# Generated by Django 5.0.4 on 2024-11-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0014_model_estadias_base64_alter_model_estadias_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_estadias',
            name='consulta',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='model_estadias',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de consulta'),
        ),
        migrations.AddField(
            model_name='model_estadias',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
