# Generated by Django 5.0.4 on 2024-11-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0015_model_estadias_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_estadias',
            name='consulta',
            field=models.IntegerField(null=True),
        ),
    ]
