# Generated by Django 5.0.4 on 2024-11-21 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0016_alter_model_estadias_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_estadias',
            old_name='consulta',
            new_name='consultas',
        ),
    ]
