# Generated by Django 5.0.4 on 2024-11-23 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0018_register_view_remove_model_estadias_consultas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_estadias',
            name='carrera',
            field=models.CharField(choices=[('ADC', 'ADC'), ('MET', 'MET'), ('QAI', 'QAI'), ('PIA', 'PIA'), ('QAM', 'QAM'), ('ERC', 'ERC'), ('IDGS', 'IDGS'), ('ITEA', 'ITEA'), ('IMET', 'IMET'), ('IER', 'IER'), ('ISIP', 'ISIP'), ('IPQ', 'IPQ'), ('LGCH', 'LGCH')], default='ADC', max_length=4),
        ),
        migrations.AlterField(
            model_name='model_estadias',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='register_view',
            name='fecha_consulta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de consulta'),
        ),
        migrations.AlterField(
            model_name='register_view',
            name='id_reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estadias.model_estadias'),
        ),
        migrations.AddConstraint(
            model_name='model_estadias',
            constraint=models.UniqueConstraint(fields=('matricula', 'proyecto'), name='unique_matricula_proyecto'),
        ),
    ]
