# Generated by Django 5.0.4 on 2024-11-23 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0021_alter_register_view_fecha_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_view',
            name='id_reporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estadias.model_estadias'),
        ),
    ]
