# Generated by Django 5.0.4 on 2024-11-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadias', '0023_alter_register_view_fecha_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_estadias',
            name='carrera',
            field=models.CharField(max_length=255),
        ),
    ]
