name: Despliegue simple a producción

on:
  push:
    branches:
      - main  # Cambia si usas otra rama

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Navegar al directorio del proyecto
        run: cd /var/www/apps/biblioteca-uts

      - name: Actualizar código desde GitHub
        run: |
          cd /var/www/apps/biblioteca-uts
          git pull origin main --rebase

      - name: Levantar contenedores (sin rebuild)
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml up -d

      - name: Ejecutar migraciones y collectstatic
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose exec -T app-biblioteca python manage.py makemigrations
          docker-compose exec -T app-biblioteca python manage.py migrate --database=default
          docker-compose exec -T app-biblioteca python manage.py collectstatic --noinput
