name: Despliegue simple a producción

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Navegar al directorio del proyecto
        run: cd /var/www/apps/biblioteca-uts

      - name: Actualizar código desde GitHub
        run: |
          cd /var/www/apps/biblioteca-uts
          git pull origin main --rebase

      - name: Ejecutar migraciones y collectstatic
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml run --rm app-biblioteca bash -c "rm -rf /code/staticfiles/*"
          docker-compose -f docker-compose-prod.yml run --rm app-biblioteca python manage.py makemigrations
          docker-compose -f docker-compose-prod.yml run --rm app-biblioteca python manage.py migrate --database=default
          docker-compose -f docker-compose-prod.yml run --rm app-biblioteca python manage.py collectstatic --noinput


      - name: Reiniciar contenedores
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml down
          sleep 15
          docker-compose -f docker-compose-prod.yml up -d
