name: Despliegue simple a producci칩n

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Navegar al directorio del proyecto
        run: cd /var/www/apps/biblioteca-uts

      - name: Actualizar c칩digo desde GitHub
        run: |
          cd /var/www/apps/biblioteca-uts
          git pull origin main --rebase

      - name: Detener contenedores en ejecuci칩n
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml down
          sleep 15
      
      - name: Construir imagen Docker
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml build --no-cache

      - name: Eliminar im치genes sin etiqueta (<none>)
        run: docker image prune -f

      - name: Ejecutar migraciones y collectstatic
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml run --rm app-biblioteca bash -c "\
            rm -rf /code/staticfiles/* && \
            python manage.py makemigrations && \
            python manage.py migrate --database=default && \
            python manage.py collectstatic --noinput"

      - name: Reiniciar contenedores
        run: |
          cd /var/www/apps/biblioteca-uts
          docker-compose -f docker-compose-prod.yml up -d
